# Local Development Docker image specifics
services:
  backup:
    build: ./
    depends_on:
      - db
    env_file:
      - service.env
  db:
    image: postgres:13.3
    environment:
      POSTGRES_PASSWORD: password
